# Generated by Django 2.2.2 on 2019-06-24 14:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flexpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('intro_block', wagtail.core.blocks.StructBlock([('h1', wagtail.core.blocks.CharBlock(required=True)), ('content', wagtail.core.blocks.TextBlock())])), ('product_block', wagtail.core.blocks.StructBlock([('products', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock('formpage.CatalogPage')))])), ('BlockWithIcon', wagtail.core.blocks.StructBlock([('h2', wagtail.core.blocks.CharBlock(required=True)), ('icon_block', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.CharBlock()), ('h3', wagtail.core.blocks.CharBlock()), ('p', wagtail.core.blocks.TextBlock())])))])), ('Text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock())]))], null=True),
        ),
    ]
