# Generated by Django 2.2.2 on 2019-08-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicache',
            name='product',
            field=models.TextField(null=True),
        ),
    ]
