# Generated by Django 2.2.2 on 2019-08-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190805_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiCache',
        ),
    ]
