# Generated by Django 2.2.2 on 2019-07-02 10:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', wagtail.core.fields.StreamField([('nav', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name', required=False)), ('pagefield', wagtail.core.blocks.PageChooserBlock(help_text='Select the page', required=False)), ('subpage', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name', required=False)), ('pagefield', wagtail.core.blocks.PageChooserBlock(help_text='Select subpage', required=False))]), blank=True, null=True))]))], blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
