# Generated by Django 2.2.2 on 2019-07-03 15:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsetting',
            name='products',
            field=wagtail.core.fields.StreamField([('nav', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name', required=False)), ('pagefield', wagtail.core.blocks.PageChooserBlock(help_text='Select the page', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navbarsetting',
            name='nav',
            field=wagtail.core.fields.StreamField([('nav', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name', required=False)), ('pagefield', wagtail.core.blocks.PageChooserBlock(help_text='Select the page', required=False))]))], blank=True, null=True),
        ),
    ]
