# Generated by Django 2.2.2 on 2019-07-04 14:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_auto_20190703_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarsetting',
            name='products',
            field=wagtail.core.fields.StreamField([('product', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(help_text='Name', required=False)), ('pagefield', wagtail.core.blocks.PageChooserBlock(help_text='Select the page', required=False))]))], blank=True, null=True),
        ),
    ]
