# Generated by Django 2.2.2 on 2019-06-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20190628_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='house_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='zip_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
