# Generated by Django 2.2.2 on 2019-07-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20190628_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
