# Generated by Django 2.2.2 on 2019-07-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_orders_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='copmany',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
