# Generated by Django 2.2.2 on 2019-07-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clients_copmany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='copmany',
            new_name='company',
        ),
    ]
