# Generated by Django 2.2.2 on 2019-07-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20190701_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name_data',
            field=models.TextField(null=True),
        ),
    ]
