# Generated by Django 2.2.2 on 2019-07-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_orders_name_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vals', models.TextField(null=True)),
                ('data_name', models.TextField(null=True)),
            ],
        ),
    ]
