# Generated by Django 2.2.2 on 2019-07-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='prices',
            field=models.TextField(null=True),
        ),
    ]
