# Generated by Django 2.2.2 on 2019-07-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_cartitems_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='product',
            new_name='slug',
        ),
    ]
