# Generated by Django 2.2.2 on 2019-07-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20190711_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('saved_name', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cart_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.CartItems')),
            ],
        ),
    ]
