# Generated by Django 2.2.2 on 2019-07-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_uploadedfile_saved_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
