# Generated by Django 2.2.2 on 2019-06-24 10:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('intro_block', wagtail.core.blocks.StructBlock([('h1', wagtail.core.blocks.CharBlock(required=True)), ('content', wagtail.core.blocks.TextBlock())]))], null=True),
        ),
    ]
