# Generated by Django 2.2.2 on 2019-08-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlugContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('area_type', models.CharField(max_length=7)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('postcode', models.CharField(max_length=15)),
                ('parent_country', models.IntegerField()),
                ('parent_county', models.IntegerField()),
                ('spinned', models.IntegerField()),
            ],
            options={
                'db_table': 'slug_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
