# Generated by Django 2.2.2 on 2019-08-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spinner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('kwargs', models.TextField(null=True)),
                ('number', models.IntegerField(max_length=11, null=True)),
                ('generated', models.IntegerField(max_length=11, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spinner.Article')),
            ],
        ),
    ]
