# Generated by Django 2.2.2 on 2019-08-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinner', '0002_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='generated',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
