# Generated by Django 2.2.2 on 2019-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formpage', '0004_auto_20190624_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogpage',
            name='list_header',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
