# Generated by Django 2.2.2 on 2019-06-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formpage', '0005_catalogpage_list_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogpage',
            name='api_value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
