# Generated by Django 2.2.2 on 2019-06-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formpage', '0006_catalogpage_api_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
