# Generated by Django 2.2.2 on 2019-08-05 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formpage', '0011_catalogpage_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formpage.CatalogPage')),
            ],
        ),
    ]
